/* 3개 앱 공통 엔진 — 세 벌로 복사돼 있던 코드에서 완전히 동일했던 부분만 모은 것.
   조각들은 ES 모듈이 아니라 파일명 순서대로 이어 붙여 하나의 스크립트로 돈다.
   `/*==SLOT:n==* /` 자리에 앱별 코드(apps/<app>/app.js)가 빌드 시 삽입된다.
   조립은 scripts/compose-engine.mjs, 자세한 건 CLAUDE.md 를 볼 것. */

/* ── 데이터: [한국어명, 영어 프롬프트, 특성 설명, 추천여부] ── */
const R=1;
const ALL_DATA = [
{id:"body", title:"카메라 바디", note:"질감과 화질의 기반 · 1대만 선택됩니다", groups:[  {label:"디지털", xg:"cam", items:[
    ["Canon EOS R5","shot on Canon EOS R5","선명하고 따뜻한 인물 색감",R],
    ["Sony A7R V","shot on Sony A7R V","고해상 정밀, 중립적이고 차가운 색",R],
    ["Nikon Z9","shot on Nikon Z9","스포츠·액션, 강한 대비"],
    ["Fujifilm GFX 100S","shot on Fujifilm GFX 100S, medium format digital","중형 디지털의 깊은 계조"],
    ["Phase One XF","shot on Phase One XF IQ4","광고·제품용 최고 해상도"],
    ["iPhone 15 Pro","shot on iPhone 15 Pro","SNS·브이로그 룩, 현실적인 스냅",R],
  ]},
  {label:"시네마 · 특수", xg:"cam", items:[
    ["ARRI Alexa 35","shot on ARRI Alexa 35","현대 영화 표준, 부드러운 하이라이트 롤오프",R],
    ["ARRI Alexa LF","shot on ARRI Alexa LF","대형 센서 시네마, 넓고 얕은 심도"],
    ["RED V-Raptor","shot on RED V-Raptor 8K","초고해상 디지털 시네마, 선명한 디테일",R],
    ["Sony Venice 2","shot on Sony Venice 2","넓은 다이내믹 레인지, 자연스러운 피부톤"],
    ["Panavision DXL2","shot on Panavision Millennium DXL2","블록버스터 스케일, 아나모픽 궁합"],
    ["35mm 시네필름","shot on 35mm motion picture film","고전 영화 질감, 자연스러운 그레인",R],
    ["16mm 필름","shot on 16mm film, Bolex","거친 그레인, 인디·다큐 감성",R],
    ["Super 8","shot on Super 8mm film","홈비디오 노스탤지어, 심한 그레인과 흔들림"],
    ["VHS 캠코더","shot on VHS camcorder","저해상 스캔라인, 90년대 아날로그"],
    ["폴라로이드","shot on Polaroid SX-70","즉석 사진 프레임, 색 바랜 파스텔"],
    ["GoPro","shot on GoPro Hero, action cam","초광각 왜곡, 몰입형 액션"],
    ["드론 (DJI)","aerial shot on DJI drone","항공 시점, 광활한 스케일",R],
  ]},
  {label:"35mm 필름", xg:"cam", items:[
    ["Leica M6","shot on Leica M6","클래식 다큐·거리사진, 자연스러운 계조",R],
    ["Canon AE-1","shot on Canon AE-1","70~80년대 스냅 감성, 따뜻한 톤",R],
    ["Nikon F3","shot on Nikon F3","단단한 보도사진 룩, 중립적 색"],
    ["Contax T2","shot on Contax T2","90년대 감성 컴팩트, 부드러운 하이라이트"],
    ["일회용 카메라","shot on a disposable film camera","거친 그레인, 플래시 스냅 느낌"],
  ]},
  {label:"중형 · 대형 필름", xg:"cam", items:[
    ["Hasselblad 500C/M","shot on Hasselblad 500C/M, 6x6 medium format","정방형 프레임, 극도로 부드러운 디테일",R],
    ["Pentax 67","shot on Pentax 67, 6x7 medium format","중형 특유의 얕은 심도, 인물 명작 룩",R],
    ["Mamiya RZ67","shot on Mamiya RZ67","패션·에디토리얼 표준, 입체감 있는 피부톤"],
    ["Rolleiflex TLR","shot on Rolleiflex TLR","빈티지 정방형, 로우앵글 시점"],
    ["Linhof 4x5","shot on Linhof 4x5 large format","초고해상 정밀 묘사, 정적인 건축·풍경"],
    ["8x10 대형","shot on 8x10 large format film","극한의 디테일과 얕은 심도, 초상 사진"],
  ]},

]},

{id:"lens", title:"렌즈 · 조리개", note:"렌즈 1개 + 조리개 1개", groups:[
  {label:"광각", xg:"focal", items:[
    ["8mm 어안","8mm fisheye lens","극단적 원형 왜곡, 실험적"],
    ["14mm 초광각","14mm ultra-wide lens","웅장한 공간감, 가장자리 왜곡"],
    ["24mm 광각","24mm wide-angle lens","환경 포함 인물, 역동적 원근",R],
    ["35mm 준광각","35mm lens","다큐멘터리 표준, 자연스러운 현장감",R],
  ]},
  {label:"표준 · 망원", xg:"focal", items:[
    ["50mm 표준","50mm lens","사람 눈과 유사한 화각, 정직한 묘사",R],
    ["85mm 인물","85mm portrait lens","가장 아름다운 인물 비례, 배경 분리",R],
    ["135mm 망원","135mm telephoto lens","강한 배경 압축, 고립된 피사체",R],
    ["200mm 망원","200mm telephoto lens","극한 압축, 스포츠·야생"],
    ["600mm 초망원","600mm super telephoto lens","야생 다큐, 배경이 완전히 뭉개짐"],
    ["100mm 매크로","100mm macro lens","초근접 접사, 미세 디테일",R],
  ]},
  {label:"특수 · 캐릭터 렌즈", xg:"focal", items:[
    ["아나모픽","anamorphic lens, oval bokeh, horizontal blue lens flare","시네마스코프 룩, 가로 플레어와 타원 보케",R],
    ["Cooke S4","Cooke S4 prime lens, Cooke Look","부드럽고 따뜻한 피부 표현"],
    ["Zeiss Master Prime","Zeiss Master Prime lens","극도로 선명하고 중립적인 묘사"],
    ["Canon K35 빈티지","vintage Canon K35 lens","70년대 소프트 플레어, 따뜻한 빛번짐"],
    ["Helios 44-2","Helios 44-2 lens, swirly bokeh","소용돌이 보케, 몽환적 배경"],
    ["Petzval","Petzval lens","강한 주변부 소용돌이, 19세기 초상 룩"],
    ["틸트시프트","tilt-shift lens","미니어처 효과 또는 건축 수직 보정",R],
    ["스플릿 다이옵터","split diopter lens","전경과 후경 동시 초점, 긴장감"],
    ["프로브 렌즈","Laowa probe lens, macro probe","곤충 시점 관통 샷, 초근접 이동"],
    ["소프트 포커스","soft focus lens, dreamy diffusion","드리미한 확산, 로맨틱 무드"],
  ]},
  {label:"조리개", xg:"ap", sub:"숫자가 작을수록 배경이 흐려집니다", items:[
    ["f/1.2 (극얕음)","shot at f/1.2, razor-thin depth of field","눈만 초점, 배경 완전 소멸"],
    ["f/1.8 (얕음)","shot at f/1.8, shallow depth of field","인물 표준, 부드러운 보케",R],
    ["f/2.8 (중간)","shot at f/2.8","피사체 분리 + 어느 정도 배경 정보",R],
    ["f/5.6 (선명)","shot at f/5.6","렌즈 최상 성능, 균형잡힌 심도"],
    ["f/8 (깊음)","shot at f/8, deep focus","전체적으로 선명, 풍경·건축",R],
    ["f/16 (전초점)","shot at f/16, everything in focus, sunstars","전체 초점, 광원의 별빛 효과"],
  ]},
]},

{id:"light", title:"조명", note:"분위기의 90%를 결정", single:false, groups:[  {label:"자연광", items:[
    ["골든아워","golden hour sunlight, warm low sun","따뜻한 황금빛 사광, 긴 그림자",R],
    ["블루아워","blue hour, cool twilight ambience","차갑고 서정적인 박명",R],
    ["정오 하드광","harsh midday sun, hard shadows","선명한 그림자, 강렬하고 건조한 인상"],
    ["흐린날 소프트","overcast soft diffused light","그림자 없는 균일한 빛, 부드러움",R],
    ["창가 사이드라이트","window sidelight, soft directional","페르메이르 회화풍 측면광",R],
    ["문라이트","moonlight, cool blue night ambience","푸른 야간, 미스터리"],
    ["갓레이","volumetric god rays, light shafts through haze","안개 속 광선 다발, 신비로움"],
  ]},
  {label:"무드 · 인공광", items:[
    ["로우키","low-key lighting, chiaroscuro, deep shadows","어둠이 지배, 누아르·서스펜스",R],
    ["하이키","high-key lighting, bright airy, minimal shadows","밝고 청량, 광고·패션",R],
    ["네온 실전등","neon practical lights, magenta and cyan glow","사이버펑크 도시 야경",R],
    ["촛불","candlelight, warm flickering firelight","아주 따뜻하고 친밀한 저조도",R],
    ["고보 그림자","gobo shadows, venetian blind patterns","블라인드 줄무늬 그림자, 누아르"],
    ["텅스텐 실내등","tungsten practical lamps, warm interior","생활감 있는 실내 전구 빛"],
    ["형광등","cold fluorescent overhead light","무미건조한 사무실·병원"],
  ]},
  {label:"인물 키 라이트", xg:"key", sub:"주광은 하나만 — 빛의 위치를 정합니다", items:[
    ["렘브란트","Rembrandt lighting, triangle of light on cheek","볼에 삼각형 빛, 고전 회화적 깊이",R],
    ["버터플라이","butterfly lighting, beauty light","코 아래 나비 그림자, 뷰티·글래머"],
    ["스플릿","split lighting, half face in shadow","얼굴 절반 어둠, 극적 긴장"],
    ["언더라이팅","underlighting from below","공포·불안한 인상"],
    ["링라이트","ring light, catchlight in eyes","눈동자 링 반사, 뷰티 유튜브 룩"],
  ]},
  {label:"역광 · 보조광", sub:"키 라이트와 함께 쓸 수 있습니다", items:[
    ["림 라이트","rim lighting, backlit edge glow","윤곽선 발광, 피사체 분리",R],
    ["백라이트 실루엣","strong backlight, silhouette","완전한 실루엣 — 앞쪽 주광 없음",R],
  ]},
  {label:"조명 기구", xg:"mod", sub:"같은 위치라도 기구에 따라 결과가 달라집니다", items:[
    ["스튜디오 소프트박스","studio softbox lighting, controlled even light","깨끗한 상업 촬영 조명",R],
    ["뷰티 디쉬","beauty dish, crisp yet flattering light with fast falloff","선명하면서 피부가 예쁜 뷰티 표준"],
    ["엄브렐라","umbrella light, broad soft wraparound","넓게 감싸는 저렴하고 부드러운 광원"],
    ["스트립박스 + 그리드","gridded strip box, narrow controlled band of light","좁고 통제된 띠 형태의 빛"],
    ["스누트","snoot, tight focused pool of light","점처럼 좁게 떨어지는 스포트"],
    ["대형 디퓨전 스크림","large diffusion scrim, very soft wraparound light","창광 같은 초연질광"],
  ]},
  {label:"광질", xg:"quality", sub:"그림자 경계가 날카로운가 부드러운가", items:[
    ["경질광 (하드)","hard direct light, crisp well-defined shadow edges","윤곽이 뚜렷한 그림자, 강렬함"],
    ["연질광 (소프트)","soft diffused light, gradual shadow transition","경계가 녹아드는 그림자, 부드러움"],
  ]},
  {label:"명암비", xg:"ratio", sub:"밝은 쪽과 그림자의 밝기 차이 — 하나만", items:[
    ["강한 명암비 8:1","high key-to-fill ratio, shadows falling to deep black","그림자가 완전히 죽는 극적 대비"],
    ["중간 명암비 4:1","moderate lighting ratio, shadows retain some detail","그림자에 디테일이 남는 표준 인물 조명",R],
    ["평탄한 조명 2:1","low lighting ratio, soft even fill, minimal shadow","거의 그림자 없는 균일한 조명"],
  ]},
  {label:"필 · 반사", sub:"그림자 쪽을 어떻게 다룰지", items:[
    ["리플렉터 필","white reflector filling the shadow side","반사판으로 그림자를 살림"],
    ["네거티브 필","black negative fill on the shadow side, deepening the shadow edge","검은 판으로 그림자를 더 눌러 입체감을 만듦"],
  ]},

]},

{id:"film", title:"필름 스톡 · 색감", note:"필름 1종 + 그레이딩 1종", groups:[  {label:"컬러 필름", xg:"stock", sub:"필름은 한 종류만 — 촬영에 쓴 매체입니다", items:[
    ["Kodak Portra 400","Kodak Portra 400 film stock","가장 아름다운 피부톤, 부드러운 파스텔",R],
    ["Kodak Ektar 100","Kodak Ektar 100 film stock","고채도 선명한 색, 풍경용",R],
    ["Kodachrome","Kodachrome film stock","60~70년대 내셔널지오그래픽 룩, 진한 레드",R],
    ["Fuji Velvia 50","Fujifilm Velvia 50 slide film","강렬한 채도의 녹색·청색, 풍경"],
    ["Fuji Pro 400H","Fujifilm Pro 400H film stock","연한 민트·파스텔, 웨딩 감성"],
    ["CineStill 800T","CineStill 800T film stock, red halation","야간 네온, 붉은 할레이션 번짐",R],
    ["Kodak Vision3 500T","Kodak Vision3 500T","현대 영화용 텅스텐 필름, 저조도",R],
  ]},
  {label:"흑백 필름", xg:"stock", sub:"컬러 필름과 배타 — 하나만", items:[
    ["Ilford HP5","Ilford HP5 Plus black and white film","클래식 다큐 흑백, 부드러운 그레인",R],
    ["Kodak Tri-X 400","Kodak Tri-X 400 black and white","거친 그레인, 보도사진의 상징",R],
    ["Ilford Delta 3200","Ilford Delta 3200, heavy grain","극한 저조도, 매우 거친 질감"],
    ["고대비 흑백","high contrast black and white, deep blacks","강렬한 명암 대비, 그래픽적"],
  ]},
  {label:"흑백 필터", xg:"bwfilter", sub:"흑백 촬영용 — 컬러와 함께 쓰지 않습니다", items:[
    ["적색 필터","red filter, dramatically darkened sky, lightened warm tones","하늘이 거의 검게, 따뜻한 계열은 밝게"],
    ["황색 필터","yellow filter, slightly darkened sky, natural tonality","자연스러운 계조 보정"],
  ]},
  {label:"컬러 그레이딩", xg:"grade", sub:"후반 보정 — 하나만 선택됩니다", items:[
    ["틸 & 오렌지","teal and orange color grading","할리우드 블록버스터 표준",R],
    ["블리치 바이패스","bleach bypass, desaturated high contrast","탈색된 거친 톤, 전쟁·스릴러"],
    ["Technicolor","Technicolor three-strip process","1950년대 뮤지컬의 화려한 원색"],
    ["디새추레이션","desaturated muted color palette","감정 절제, 차분하고 현실적",R],
    ["파스텔","soft pastel color palette","동화적이고 부드러운 무드",R],
    ["세피아","sepia tone, aged photograph","오래된 사진, 과거 회상"],
    ["크로스 프로세스","cross-processed film, shifted colors","비틀린 색, 실험적 90년대"],
    ["어스 톤","earthy natural tones, warm browns and greens","자연주의, 서부극·시골"],
    ["네온 사이버펑크","cyberpunk neon palette, magenta and electric blue","형광 마젠타·블루, 미래 도시",R],
    ["웜 그레이드","warm color grade, amber highlights","전체를 따뜻하게 밀어올림"],
    ["쿨 그레이드","cool color grade, blue-shifted shadows","전체를 차갑게 내림"],
    ["스플릿 토닝","split toning, warm highlights and cool shadows","하이라이트는 따뜻, 그림자는 차갑게"],
  ]},

]},

{id:"shot", title:"샷 타입 · 앵글", note:"프레이밍과 시점", single:false, groups:[  {label:"샷 사이즈", xg:"size", sub:"1개만 선택됩니다", items:[
    ["익스트림 와이드","extreme wide shot, establishing shot","인물이 점처럼, 환경 압도",R],
    ["와이드 / 풀샷","wide shot, the entire subject visible within the frame","피사체 전체와 배경을 함께",R],
    ["미디엄 샷","medium shot, the subject occupying the middle of the frame","대화 장면 표준 · 인물은 허리 위",R],
    ["미디엄 클로즈업","medium close-up, tight framing on the upper part of the subject","인터뷰 표준 · 인물은 가슴 위"],
    ["클로즈업","close-up shot, the subject fills most of the frame","피사체가 화면을 채움 · 감정 전달의 핵심",R],
    ["익스트림 클로즈업","extreme close-up, frame-filling subject detail","피사체 일부를 화면 가득 정밀하게 강조",R],
  ]},
  {label:"앵글 · 시점", xg:"angle", items:[
    ["아이 레벨","eye level angle","중립적이고 자연스러운 시선",R],
    ["로우 앵글","low angle shot, looking up","피사체를 강하고 위압적으로",R],
    ["하이 앵글","high angle shot, looking down","피사체를 작고 취약하게",R],
    ["더치 앵글","dutch angle, tilted horizon","불안정과 혼란"],
    ["버즈 아이","bird's eye view, top-down overhead","기하학적 패턴, 신의 시점"],
    ["웜즈 아이","worm's eye view, from ground level","극단적 아래 시점, 초현실"],
    ["POV","POV shot, first person perspective","1인칭 몰입"],
  ]},
  {label:"인물 관계 프레이밍", sub:"두 인물의 관계를 보여주는 프레이밍", items:[
    ["오버 더 숄더","over-the-shoulder shot","대화의 시점 연결"],
    ["투 샷","two shot, two subjects in frame","관계성 표현"],
  ]},
  {label:"구도 원칙", sub:"여러 개 조합 가능", items:[
    ["삼분할 구도","rule of thirds composition, subject offset from center","중심을 비껴 배치, 가장 기본적인 안정 구도",R],
    ["리딩 라인","strong leading lines drawing the eye toward the subject","선이 시선을 피사체로 끌고 감"],
    ["네거티브 스페이스","generous negative space around the subject, minimalist composition","여백을 크게 — 고요함과 고립"],
    ["프레임 인 프레임","framed through a doorway or window, frame within a frame","문·창을 통해 들여다보는 이중 프레임"],
    ["전경 요소","out-of-focus foreground element framing the edge of the frame","흐린 전경으로 깊이를 만듦"],
    ["대각 구도","strong diagonal composition creating movement","대각선으로 역동감 부여"],
    ["반사 활용","subject mirrored in a reflective surface","물·유리에 비친 상을 함께 담음"],
    ["소실점 원근","one-point perspective with a strong vanishing point","한 점으로 모이는 강한 원근"],
    ["대칭 구도","perfectly symmetrical composition, centered","웨스 앤더슨 룩, 강한 형식미",R],
  ]},
  {label:"얼굴 방향", xg:"face", sub:"인물 촬영 — 하나만", items:[
    ["정면","facing the camera straight on","대칭적이고 직접적"],
    ["3/4 각도","three-quarter view of the face","가장 입체적인 표준 인물 각도",R],
    ["옆모습","profile view, side of the face","선을 강조, 서사적 거리감"],
    ["뒷모습","seen from behind, facing away from the camera","익명성과 여백"],
  ]},
  {label:"시선", xg:"gaze", items:[
    ["카메라 응시","looking directly into the lens, direct eye contact","관객과 직접 대면",R],
    ["시선 이탈","looking away from the camera, off-camera gaze","사색적·관찰적 분위기"],
  ]},

]},

{id:"move", title:"카메라 무빙", note:"동영상용 · 무빙 1개 + 시간 표현 1개", groups:[
  {label:"기본 무빙", xg:"move", items:[
    ["고정 (트라이포드)","static tripod shot, locked-off camera","완전히 정적, 관조적",R],
    ["슬로우 푸시인","slow dolly push-in","서서히 다가감, 긴장 고조",R],
    ["풀 아웃","slow dolly pull-out, reveal","물러나며 상황 노출"],
    ["트래킹 샷","tracking shot, camera follows subject","피사체와 함께 이동",R],
    ["팬","smooth pan across the scene","좌우 회전, 공간 스캔"],
    ["틸트","slow tilt up","상하 회전, 규모 드러냄"],
    ["핸드헬드","handheld camera, subtle shake","현장감·긴박감",R],
    ["스테디캠 롱테이크","steadicam long take, fluid continuous move","끊김 없는 유려한 이동"],
  ]},
  {label:"고급 · 특수 무빙", xg:"move", items:[
    ["돌리 줌","dolly zoom, vertigo effect","배경만 왜곡, 심리적 충격",R],
    ["집 크레인","crane shot, rising jib move","위로 솟구치며 스케일 확장"],
    ["짐벌 오빗","gimbal orbit around subject, 360 arc","피사체 주위 원형 회전",R],
    ["휩 팬","whip pan transition","초고속 팬, 장면 전환"],
    ["크래시 줌","crash zoom in","급격한 줌, 강조와 코믹"],
    ["FPV 드론","FPV drone fly-through, fast continuous motion","공간을 관통하는 고속 비행"],
    ["항공 상승","aerial drone rising shot","공중으로 올라가며 전경 노출",R],
    ["원형 랩어라운드","camera slowly wraps around the subject","극적 강조를 위한 감싸기"],
  ]},
  {label:"포커스 연출", sub:"무빙과 조합 가능", items:[
    ["랙 포커스","rack focus between foreground and background","초점 이동으로 시선 유도"],
  ]},
  {label:"시간 표현", xg:"time", items:[
    ["슬로우 모션","slow motion, 120fps overcranked","고속 촬영, 우아한 느림",R],
    ["초고속","ultra slow motion, 1000fps phantom","물방울·파열의 순간 포착"],
    ["타임랩스","time-lapse","시간 압축, 구름·인파 흐름",R],
    ["하이퍼랩스","hyperlapse, moving time-lapse","이동하며 시간 압축"],
    ["실시간 롱테이크","real-time continuous long take","컷 없는 몰입"],
  ]},
  {label:"움직임의 크기", xg:"amount", sub:"모델이 얼마나 크게 움직일지", items:[
    ["미세한 움직임","subtle minimal motion, almost still","숨결·머리카락 정도만 흔들림",R],
    ["보통 움직임","moderate natural motion","자연스러운 일상적 움직임",R],
    ["역동적 움직임","dynamic energetic motion, dramatic movement","크고 빠른 동작",R],
  ]},
  {label:"장면 제어", sub:"영상 모델의 폭주를 막는 지시문", items:[
    ["한 장면 유지","one single continuous take, the scene stays the same throughout","장면이 바뀌지 않고 하나의 컷으로 이어집니다",R],
    ["24fps 시네마틱","24fps cinematic frame rate","영화 특유의 잔상감",R],
    ["60fps 부드럽게","60fps smooth motion","매끄럽고 선명한 움직임"],
    ["끊김 없는 루프","seamless loop, the first and last frame match","처음과 끝이 이어지는 반복 영상"],
    ["피사체 정지","the subject stays still while the environment moves","인물은 그대로, 배경만 살아 움직임"],
    ["카메라 고정 유지","locked-off camera","카메라가 움직이지 않고 고정됩니다"],
  ]},
]},

{id:"tech", title:"기술 디테일", note:"마감 품질을 올리는 요소", single:false, groups:[  {label:"심도 · 셔터", items:[
    ["얕은 심도 보케","shallow depth of field, creamy bokeh","배경을 크림처럼 뭉갬",R],
    ["딥 포커스","deep focus, everything sharp","전경부터 원경까지 선명",R],
    ["프리즈 (1/2000s)","1/2000s shutter speed, frozen motion","움직임 완전 정지"],
    ["모션 블러 (1/15s)","1/15s shutter speed, motion blur","흐름과 속도감",R],
    ["장노출","long exposure, light trails","빛 궤적, 물의 실크 표현"],
    ["180도 셔터","180-degree shutter rule, natural motion blur","영화적으로 자연스러운 잔상"],
  ]},
  {label:"초점 지점", xg:"fp", sub:"심도의 '깊이'가 아니라 '어디에' 맞추는지", items:[
    ["눈에 초점","critical focus on the eyes","인물 사진의 기본 — 눈이 가장 선명",R],
    ["전경 초점","focus on the foreground element, subject soft behind","앞을 살리고 피사체를 흐리게"],
    ["의도적 초점 이탈","subject slightly out of focus, intentional soft focus miss","일부러 빗나간 초점, 몽롱한 감성"],
  ]},
  {label:"노출", xg:"expo", sub:"조리개·셔터·ISO의 결과", items:[
    ["1스톱 오버","deliberately overexposed by one stop, bright airy exposure","밝고 통풍감 있는 감성 노출"],
    ["정확 노출","accurate balanced exposure","기준대로 맞춘 노출"],
    ["1스톱 언더","deliberately underexposed by one stop, moody dark exposure","어둡고 무거운 분위기"],
  ]},
  {label:"감도 · 화이트밸런스", items:[
    ["ISO 100 클린","ISO 100, clean noise-free image","노이즈 없는 최상 화질",R],
    ["ISO 3200 그레인","ISO 3200, visible grain","거친 저조도 질감",R],
    ["텅스텐 WB","tungsten white balance, cool blue shift","푸른 야간 톤"],
    ["데이라이트 WB","daylight white balance","자연스러운 주광 색"],
    ["믹스드 라이팅","mixed color temperature lighting","따뜻함과 차가움의 공존"],
  ]},
  {label:"광학 필터", sub:"촬영 시 렌즈 앞에 끼우는 필터", items:[
    ["폴라라이저","polarizing filter, deep saturated sky and removed reflections","하늘이 진해지고 반사가 사라짐"],
    ["ND 필터","neutral density filter allowing a wide aperture in bright light","밝은 낮에도 조리개를 열 수 있게"],
    ["그라데이션 ND","graduated neutral density filter, sky balanced with the foreground","하늘만 눌러 노출 균형"],
  ]},
  {label:"톤 · 대비", sub:"대비 1개 + 섀도 처리 1개 조합 가능", items:[
    ["저대비 플랫","low contrast flat tonal profile","계조가 완만한 시네마 플랫 룩"],
    ["고대비 톤","high contrast tonality, deep blacks and bright highlights","강렬한 명암 대비"],
    ["블랙 크러시","crushed blacks, shadows falling to pure black","그림자를 완전히 눌러 검게"],
    ["리프티드 블랙","lifted blacks, milky shadows","검정이 들려 올라간 필름 베이스 느낌"],
    ["하이라이트 롤오프","gentle highlight rolloff, highlights retained smoothly into the white point","밝은 부분이 부드럽게 넘어감"],
  ]},
  {label:"렌즈 아티팩트", items:[
    ["렌즈 플레어","lens flare streaking across the frame","가로로 뻗는 시네마틱 빛줄기",R],
    ["할레이션","halation, red glow around highlights","하이라이트 주변 붉은 번짐"],
    ["비네팅","subtle vignetting","가장자리 어둡게, 시선 집중",R],
    ["필름 그레인","natural film grain","아날로그 질감",R],
    ["크로마틱 애버레이션","slight chromatic aberration","경계의 색수차, 빈티지"],
    ["블룸","soft highlight bloom","빛이 번지는 몽환적 효과"],
    ["렌즈 디퓨전","Black Pro-Mist diffusion filter","하이라이트를 부드럽게, 영화적"],
  ]},
  {label:"해상도 · 다이내믹 레인지", items:[
    ["8K 고해상","8K resolution, ultra detailed","극한 디테일 요구"],
    ["HDR","HDR, high dynamic range","밝은 곳과 어두운 곳 모두 살림"],
  ]},

]},
];
